// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;

namespace DBContexts.OIDC_Management.Entities;

public partial class AspNetUserLogin : IdentityUserLogin<string>
{
    //public string LoginProvider { get; set; }

    //public string ProviderKey { get; set; }

    //public string ProviderDisplayName { get; set; }

    //public string UserId { get; set; }

    public virtual AspNetUser User { get; set; }
}