// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;

namespace DBContexts.OIDC_Management.Entities;

public partial class AspNetUserClaim : IdentityUserClaim<string>
{
    //public int Id { get; set; }

    //public string UserId { get; set; }

    //public string ClaimType { get; set; }

    //public string ClaimValue { get; set; }

    public virtual AspNetUser User { get; set; }
}