// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBContexts.OIDC_Management.Entities;

public partial class Client
{
    public string ClientId { get; set; }

    public string ClientSecret { get; set; }

    public string DisplayName { get; set; }

    public string RedirectUris { get; set; }

    public string SignOutCallbackPath { get; set; }

    public string CallbackPath { get; set; }

    public string AccessDeniedPath { get; set; }

    public string Scope { get; set; }

    public string GrantType { get; set; }

    public string Authority { get; set; }

    public string KeyWord { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? Status { get; set; }

    public string FrontChannelLogoutUri { get; set; }

    public virtual ICollection<RefreshToken> RefreshTokens { get; set; } = new List<RefreshToken>();

    public virtual ICollection<UserSession> UserSessions { get; set; } = new List<UserSession>();
}