// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBContexts.OIDC_Management.Entities;

public partial class RefreshToken
{
    public readonly RefreshToken[] Items;

    public long Id { get; set; }

    public string Token { get; set; }

    public string UserId { get; set; }

    public string ClientId { get; set; }

    public string Scope { get; set; }

    public string Nonce { get; set; }

    public DateTime CreatedTime { get; set; }

    public DateTime ExpiresTime { get; set; }

    public virtual Client Client { get; set; }

    public virtual AspNetUser User { get; set; }
}