// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBContexts.OIDC_Management.Entities;

public partial class Setting
{
    public int Id { get; set; }

    public string Section { get; set; }

    public string Value { get; set; }

    public string UpdateBy { get; set; }

    public DateTime? UpdateDate { get; set; }

    public string Note { get; set; }
}