// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBContexts.OIDC_Management.Entities;

public partial class Setting
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int? Value { get; set; }
}