// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBContexts.OIDC_Management.Entities;

public partial class UserSession
{
    public string UserId { get; set; }

    public string ClientId { get; set; }

    public string SessionState { get; set; }

    public DateTime? CreatedTime { get; set; }

    public DateTime? LastAccessTime { get; set; }

    public DateTime? ExpiresTime { get; set; }

    public int? IsActive { get; set; }

    public long Id { get; set; }

    public virtual Client Client { get; set; }

    public virtual ICollection<RefreshToken> RefreshTokens { get; set; } = new List<RefreshToken>();

    public virtual AspNetUser User { get; set; }
}