// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBContexts.OIDC.Entities;

public partial class Client
{
    public string ClientId { get; set; }

    public string ClientSecret { get; set; }

    public string DisplayName { get; set; }

    public string RedirectUris { get; set; }

    public string PostLogoutRedirectUris { get; set; }

    public string AllowedScopes { get; set; }

    public string GrantTypes { get; set; }

    public string KeyWord { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? Status { get; set; }
}