// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBContext.EmployeeMangement.Entities;
public partial class Department
{
    public int Id { get; set; }

    public string Keyword { get; set; }

    public int? Status { get; set; }

    public int? CreateBy { get; set; }

    public DateTime? CreateDate { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public int? ManagerId { get; set; }

    public int? JobPositionId { get; set; }

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();

    public virtual JobPosition JobPosition { get; set; }

    public virtual Employee Manager { get; set; }
    public virtual Employee CreateByNavigation { get; set; }
    public virtual Employee UpdateByNavigation { get; set; }

}