// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBContext.EmployeeMangement.Entities;

public partial class Employee
{
    public int Id { get; set; }

    public string Keyword { get; set; }

    public int? Status { get; set; }

    public int? CreateBy { get; set; }

    public DateTime? CreateDate { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string Fullname { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public int? JobPositionId { get; set; }

    public int? DepartmentId { get; set; }

    public string Position { get; set; }

    public int? Role { get; set; }

    public int? MediaId { get; set; }

    public string PasswordHash { get; set; }

    public virtual Department Department { get; set; }

    public virtual ICollection<Department> Departments { get; set; } = new List<Department>();
    public virtual ICollection<JobPosition> JobPositionsCreated { get; set; } = new List<JobPosition>();
    public virtual ICollection<JobPosition> JobPositionsUpdated { get; set; } = new List<JobPosition>();

    public virtual JobPosition JobPosition { get; set; }

    public virtual MediaFile Media { get; set; }
}