// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBContext.EmployeeMangement.Entities;

public partial class MediaFile
{
    public int Id { get; set; }

    public string Keyword { get; set; }

    public int? Status { get; set; }

    public int? CreateBy { get; set; }

    public DateTime? CreateDate { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string FileName { get; set; }

    public string FilePath { get; set; }

    public double? FileSize { get; set; }

    public string MimeType { get; set; }

    public string FileCode { get; set; }

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();
}