// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DBContexts.LoginManagement.Entities.Models;

public partial class LoginManagementContext : DbContext
{
    public LoginManagementContext(DbContextOptions<LoginManagementContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Client> Clients { get; set; }

    public virtual DbSet<Employee> Employees { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Client>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Clients__3214EC072620667B");

            entity.HasIndex(e => e.ClientId, "UQ__Clients__E67E1A2531DE6934").IsUnique();

            entity.Property(e => e.AllowedSsoproviders)
                .HasMaxLength(255)
                .HasColumnName("AllowedSSOProviders");
            entity.Property(e => e.ClientId)
                .IsRequired()
                .HasMaxLength(225);
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Secret).HasMaxLength(255);
            entity.Property(e => e.Status).HasDefaultValue(1);
            entity.Property(e => e.SubRestKey)
                .IsRequired()
                .HasMaxLength(225);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Employee>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Employee__3214EC07E8254566");

            entity.HasIndex(e => e.Email, "UQ__Employee__A9D1053493EF67E5").IsUnique();

            entity.Property(e => e.AccessToken).HasMaxLength(255);
            entity.Property(e => e.AccessTokenExpiry).HasColumnType("datetime");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.EmailVerified).HasDefaultValue(false);
            entity.Property(e => e.FullName).IsRequired();
            entity.Property(e => e.LastLoginDate).HasColumnType("datetime");
            entity.Property(e => e.LoginMethods).HasMaxLength(50);
            entity.Property(e => e.PasswordEncodeKey).HasMaxLength(255);
            entity.Property(e => e.PasswordHash).HasMaxLength(255);
            entity.Property(e => e.Phone)
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.RefreshToken).HasMaxLength(255);
            entity.Property(e => e.RefreshTokenExpiry).HasColumnType("datetime");
            entity.Property(e => e.Role).HasDefaultValue(0);
            entity.Property(e => e.SsoProvider).HasMaxLength(50);
            entity.Property(e => e.SsoSub).HasMaxLength(255);
            entity.Property(e => e.Status).HasDefaultValue(1);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.CreateByNavigation).WithMany(p => p.EmployeeCreateByNavigations)
                .HasForeignKey(d => d.CreateBy)
                .HasConstraintName("FK_Employees_CreateBy");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.EmployeeUpdatedByNavigations)
                .HasForeignKey(d => d.UpdatedBy)
                .HasConstraintName("FK_Employees_UpdatedBy");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}