// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using DBContext.EmployeeMangement.Entities;
namespace DBContext.EmployeeMangement;

public partial class EmployeeManagementContext : DbContext
{
    public EmployeeManagementContext(DbContextOptions<EmployeeManagementContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Department> Departments { get; set; }

    public virtual DbSet<Employee> Employees { get; set; }

    public virtual DbSet<JobPosition> JobPositions { get; set; }

    public virtual DbSet<MediaFile> MediaFiles { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Department>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Departme__3214EC070C1E8131");

            entity.Property(e => e.Code).HasMaxLength(225);
            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.Name).HasMaxLength(225);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.JobPosition).WithMany(p => p.Departments)
                .HasForeignKey(d => d.JobPositionId)
                .HasConstraintName("FK_Departments_JobPositions");

            entity.HasOne(d => d.Manager).WithMany(p => p.Departments)
                .HasForeignKey(d => d.ManagerId)
                .HasConstraintName("FK_Departments_Employees");

            entity.HasOne(d => d.CreateByNavigation)
        .WithMany()
        .HasForeignKey(d => d.CreateBy)
        .HasConstraintName("FK_Department_CreateBy_Employee");

            entity.HasOne(d => d.UpdateByNavigation)
        .WithMany()
        .HasForeignKey(d => d.UpdatedBy)
        .HasConstraintName("FK_Department_UpdateBy_Employee");
        });

        modelBuilder.Entity<Employee>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Employee__3214EC07E4475CF0");

            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.PasswordHash)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.Phone)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Position).HasMaxLength(255);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.Department).WithMany(p => p.Employees)
                .HasForeignKey(d => d.DepartmentId)
                .HasConstraintName("FK_Employees_Departments");

            entity.HasOne(d => d.JobPosition).WithMany(p => p.Employees)
                .HasForeignKey(d => d.JobPositionId)
                .HasConstraintName("FK_Employees_JobPositions");

            entity.HasOne(d => d.Media).WithMany(p => p.Employees)
                .HasForeignKey(d => d.MediaId)
                .HasConstraintName("FK_Employees_MediaFiles");
        });

        modelBuilder.Entity<JobPosition>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__JobPosit__3214EC07B2BCF9AD");

            entity.Property(e => e.Address).HasMaxLength(255);
            entity.Property(e => e.Code).HasMaxLength(225);
            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.Name).HasMaxLength(225);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            entity.HasOne(jp => jp.CreateByNavigation)
    .WithMany(emp => emp.JobPositionsCreated)
    .HasForeignKey(jp => jp.CreateBy)
    .HasConstraintName("FK_JobPosition_CreateBy");

            entity.HasOne(jp => jp.UpdateByNavigation)
                .WithMany(emp => emp.JobPositionsUpdated)
                .HasForeignKey(jp => jp.UpdatedBy)
                .HasConstraintName("FK_JobPosition_UpdateBy");

        });

        modelBuilder.Entity<MediaFile>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__MediaFil__3214EC07BCE0E786");

            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.FileCode).HasMaxLength(255);
            entity.Property(e => e.MimeType).HasMaxLength(225);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}