// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBContexts.LoginManagement.Entities;

public partial class Client
{
    public int Id { get; set; }

    public string ClientId { get; set; }

    public string Keyword { get; set; }

    public int? Status { get; set; }

    public int? CreateBy { get; set; }

    public DateTime? CreateDate { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string FullName { get; set; }

    public string SubRestKey { get; set; }

    public string AllowedSsoproviders { get; set; }

    public string RedirectUris { get; set; }

    public string Secret { get; set; }

    public virtual ICollection<Employee> EmployeeCreateByNavigations { get; set; } = new List<Employee>();

    public virtual ICollection<Employee> EmployeeUpdatedByNavigations { get; set; } = new List<Employee>();
}