// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBContexts.LoginManagement.Entities;

public partial class Employee
{
    public int Id { get; set; }

    public string Keyword { get; set; }

    public int? Status { get; set; }

    public int? CreateBy { get; set; }

    public DateTime? CreateDate { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string PasswordHash { get; set; }

    public string PasswordEncodeKey { get; set; }

    public string SsoProvider { get; set; }

    public string SsoSub { get; set; }

    public bool? EmailVerified { get; set; }

    public DateTime? LastLoginDate { get; set; }

    public string LoginMethods { get; set; }

    public string AccessToken { get; set; }

    public string RefreshToken { get; set; }

    public DateTime? AccessTokenExpiry { get; set; }

    public DateTime? RefreshTokenExpiry { get; set; }

    public int? Role { get; set; }

    public virtual Client CreateByNavigation { get; set; }

    public virtual Client UpdatedByNavigation { get; set; }
}